# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about
    weight: 20
  - name: Uses
    url: /uses
    weight: 30
  - name: Blog
    url: /blog
    weight: 35
  - name: Now
    url: /now
    weight: 40
  - name: Books
    url: /#books
    weight: 50
